### PR TITLE
Make determining type of error more robust

### LINKED ISSUE #87: XML writer incorrectly assumes that error types can be parsed
[This code](https://github.com/JuliaTesting/TestReports.jl/blob/d120625993e279b2d95838fcc8eb511de58c7aa9/src/to_xml.jl#L269-L277) assumes that we can call `Meta.parse` on the error type, but this doesn't seem to be a reliable assumption

For instance, the putting the following in a test script and running with TestReports:

```julia
run(`false`)
```

gives

```
ERROR: UndefVarError: ProcessExited not defined
Stacktrace:
  [1] top-level scope
    @ none:1
  [2] eval
    @ ./boot.jl:373 [inlined]
  [3] eval
    @ ~/.julia/packages/TestReports/lwcSU/src/TestReports.jl:1 [inlined]
  [4] get_error_info(v::Test.Error)
    @ TestReports ~/.julia/packages/TestReports/lwcSU/src/to_xml.jl:271
  [5] to_xml(v::Test.Error)
    @ TestReports ~/.julia/packages/TestReports/lwcSU/src/to_xml.jl:246
  [6] to_xml
    @ ~/.julia/packages/TestReports/lwcSU/src/to_xml.jl:251 [inlined]
  [7] (::TestReports.var"#6#7"{ReportingTestSet})(result::TestReports.ReportingResult{Test.Error})
    @ TestReports ~/.julia/packages/TestReports/lwcSU/src/to_xml.jl:194
  [8] iterate
    @ ./generator.jl:47 [inlined]
  [9] _collect(c::Vector{Test.Result}, itr::Base.Generator{Vector{Test.Result}, TestReports.var"#6#7"{ReportingTestSet}}, #unused#::Base.EltypeUnknown, isz::Base.HasShape{1})
    @ Base ./array.jl:744
 [10] collect_similar(cont::Vector{Test.Result}, itr::Base.Generator{Vector{Test.Result}, TestReports.var"#6#7"{ReportingTestSet}})
    @ Base ./array.jl:653
 [11] map(f::Function, A::Vector{Test.Result})
    @ Base ./abstractarray.jl:2867
 [12] to_xml(ts::ReportingTestSet)
    @ TestReports ~/.julia/packages/TestReports/lwcSU/src/to_xml.jl:193
 [13] (::TestReports.var"#4#5")(result::ReportingTestSet)
    @ TestReports ~/.julia/packages/TestReports/lwcSU/src/to_xml.jl:147
 [14] iterate
    @ ./generator.jl:47 [inlined]
 [15] _collect(c::Vector{Test.AbstractTestSet}, itr::Base.Generator{Vector{Test.AbstractTestSet}, TestReports.var"#4#5"}, #unused#::Base.EltypeUnknown, isz::Base.HasShape{1})
    @ Base ./array.jl:744
 [16] collect_similar(cont::Vector{Test.AbstractTestSet}, itr::Base.Generator{Vector{Test.AbstractTestSet}, TestReports.var"#4#5"})
    @ Base ./array.jl:653
 [17] map(f::Function, A::Vector{Test.AbstractTestSet})
    @ Base ./abstractarray.jl:2867
 [18] report(ts::ReportingTestSet)
    @ TestReports ~/.julia/packages/TestReports/lwcSU/src/to_xml.jl:146
 [19] top-level scope
    @ none:16
ERROR: TestReports failed to generate the report.
See error log above.
```

which seems to be because the error is a `ProcessFailedException` but `showerror` gives:

```
failed process: Process(`false`, ProcessExited(1))
```

which is obviously not parseable.

A different flavor, if I have a custom error type:

```julia
module Temp
struct MyError <: Exception end
end
```

then `throw(Temp.MyError())` in the tests gives

```
ERROR: UndefVarError: Temp not defined
...
ERROR: TestReports failed to generate the report.
See error log above.
```

because `showerror` prints `Temp.MyError()`

I don't know enough to say what should be done instead, but just wanted to share in case there is an easy fix

### PR DESCRIPTION
**Pull request by mmiller-max**
Closes #87

### CODE REVIEW

File: src/to_xml.jl [hunk 1]
```diff
@@ -268,19 +268,39 @@ function get_error_info(v::Error)
...
+    catch e
+        # Fallback, produces ugly output but at least it's there
+        return err_string
+    end
+end
+
+function parse_error_msg(err_string)
+    local err
+    try
+        err = eval(Meta.parse(err_string))
```
Comment (oxinabox) [inline src/to_xml.jl:297]: I sure do hate this.
But we don't have a choice since they started stringifying everything.
(Nothing actionable here)

**Review by oxinabox — APPROVED** [review]

File: src/to_xml.jl (hunk 1 above)
Comment (mmiller-max) [reply src/to_xml.jl:297]: Yea it doesn't feel super nice
