### PR TITLE
Runner code checks for problems against flattened testsets

### LINKED ISSUE #118: Erroneous return code and "test passed" message
We've recently had trouble with `TestReports >= v1.0.0`. Our testing pipelines were erroneously succeeding even though some tests were failing (which was correctly documented in the generated xml). We've successfully tracked this down to the fact that the runner code from `gen_runner_code` in `src/runner.jl` only checks for failed results and determines the exit code *after* flattening the results.

This MWE shows the problem with that:

```julia
using Test, TestReports
ts = @testset ReportingTestSet "" begin
    @testset "mytestset" begin
        @test 1==1
        @testset "level2testset" begin
            @test 1==2
        end
    end
end

println("Before flattening: $(any_problems(ts))")
fr = TestReports.flatten_results!(ts)
println("After flattening: $(any_problems(ts))")
```
with the output

```
level2testset: Test Failed at /home/philip/Documents/DiskCellDesign/TestReports.jl/src/bug.jl:6
  Expression: 1 == 2
   Evaluated: 1 == 2

Stacktrace:
# omitted for brevity

Test Summary:   | Pass  Fail  Total  Time
mytestset       |    1     1      2  0.0s
  level2testset |          1      1  0.0s
Before flattening: true
After flattening: false
```

I think I know exactly what's happening: `_flatten_results!` is using the original testset "mytestset" to wrap any bare results, replacing the original vector of results, so all results which were already themselves testsets, like "level2testset" in the example, simply disappear from the testset. Instead, they are returned via the resulting flattened vector, `fr` in the above case. This is why the xml written by the runner code is correct, but the test with `any_problems` fails. This problem doesn't occur if the testset doesn't contain any bare results that need to be wrapped, because the original testset is not modified in this case.

This seems to be easy to fix by either testing with `any_problems` before flattening, or using `any(any_problems.(fr))` on the flattened vector instead.

But before I make a pull request to implement this, I would like to confirm that this is not just an unintentional side effect of `flatten_results!`. I.e., is `flatten_results!` indeed meant to make the original testset unusable, so the problem should be fixed in the runner code (and not in `_flatten_results!` itself)?

### PR DESCRIPTION
**Pull request by omus**
Fixes #118.

### CODE REVIEW

File: src/runner.jl [hunk 1]
```diff
@@ -151,10 +151,11 @@ function gen_runner_code(testfilename, logfilename, test_args)
         end
 
         # Flatten before calling `report` to avoid a `deepcopy`.
+        flattened_testsets = TestReports.flatten_results!(ts)
         open($(repr(logfilename)), "w") do io
-            prettyprint(io, report(TestReports.flatten_results!(ts)))
+            prettyprint(io, report(flattened_testsets))
         end
-        any_problems(ts) && exit(TestReports.TESTS_FAILED)
+        any_problems(flattened_testsets) && exit(TestReports.TESTS_FAILED)
```
Comment (omus) [inline src/runner.jl:158]: We're now properly testing against the scenario in #118 with the new "FailedNestedTest" package. By chaing this line to:
```julia
        any_problems(ts) && exit(TestReports.TESTS_FAILED)
```
results in the following test failure:
```
Test Summary:    | Pass  Fail  Total  Time
FailedNestedTest |    1     1      2  0.1s
  nested         |          1      1  0.1s
[ Info: FailedNestedTest tests passed. Results saved to /Users/cvogt/.julia/dev/TestReports/test/testlog.xml.
Test packages: Test Failed at /Users/cvogt/.julia/dev/TestReports/test/utils.jl:132
  Expression: TestReports.test(pkg)
    Expected: TestReports.PkgTestError
  No exception thrown
```

**Comment by philbit** [comment]
I suggest updating the docs of `flatten_results!` as in #120

**Review by oxinabox — APPROVED** [review]
